spring.application.name=MMT
server.port=8080

# IRCTC Service base URL
irctc.base-url=http://localhost:8081

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
